{% set data = load_setup_py_data() %}

package:
  name: q2-feature-table
  version: {{ data.get('version') }}

source:
  path: ../..
build:
  noarch: python
  script: python setup.py install

requirements:
  build:
    - python 3.5*
    - setuptools
    - scikit-bio
    - biom-format
    - h5py
    - seaborn
    - numpy
    - ipywidgets
    - qiime2 2017.3.*
    - q2templates 2017.3.*
    - q2-types 2017.3.*

  run:
    - python 3.5*
    - setuptools
    - scikit-bio
    - biom-format
    - h5py
    - seaborn
    - numpy
    - ipywidgets
    - qiime2 2017.3.*
    - q2templates 2017.3.*
    - q2-types 2017.3.*

test:
  imports:
    - q2_feature_table
    - qiime2.plugins.feature_table

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
